language: python
python:
- '3.5'
install:
- pip install -r requirements.txt
script:
- python -m pytest Test
- python -m pytest Legobot/LegoTests
- bandit -r .
- flake8 .
notifications:
  travis:
    slack:
      secure: "zU3i5HFizN1UvIcmr3jTGX4J/48Kukau2dxC5LCaTzpc0QzM30caOTXBQrrYUoKxmLxx5HooVswGtK2ljo53lx8HK3zwPtFJLCBjuG48xFh2Ow4DUUEmNJa5uBkNJxfuJV9dT+jFg4WiS1YbxJbDs25SMsSzJpxZFCnlgYrIqMK6f1gDsNKQg4k6bTViu8Ugp6ibAPt1PRtep3adXNr0TE8Iwg2KFC74pDnPRh3B3TUmqESmIZOObJ2b0mDM1KGRY+N5vpQ7r3h+eaFhvbRD0HJPRttBfzB10YegtOe/c1OTEf+zj9BaoMBJv/G095qJc3HqHy7L28ZJQGzWOsYv5ypclGaowbFLQ+G2tw6YjfLNyx+F4pwmtVDv1+46svzeuwJHufCDUBZMqNSGLRx+dyD+4lbYmwNtYow+hCU7JDpnIixM/jFwbn7jZw+UVao1vH2G8emYIjmcSVnZkYjqclLUTgIYh1a3Ovzj+orA6dz9kIMZeDjtWcbcyiJTm8y6C7+uQZvepp5qCXH5ieyA+6h3rDZKuz+4vw94/7WdDQ0oM4QYvrMGXXVhhYPK7GRTHOVkgcstefZ69XyCANYiO1pU4ntxBiJrzB/Q1A5docmV5zT1a4wpNeRhXj+YrMUcmIP/56u/b/YTYsYed0WRqAcAv1CcpONkyOZc9IZ/KQE="
deploy:
  provider: pypi
  user: briggsb
  password:
    secure: e95p+v9HRzAnraAy5LvqT77v0nzFyjAWDOw1twsI1rw77i2trklaXqRpeld1U9OsRqlxDdGc6pqCwu2ZRO/puSOGd5TU4Cr64mnW3IEep57lD5wPFVC9e58ErYU33DZoTZYixH76ftK+ZvSNRYkZbHLeXasyJtC7q87R22cCqjfln1dlTia/D6xU8NVqmf9P8fohTKw6xKHYcKZVT2FHCGLNS/VTu8iHXiRi2KdfZbiuqYwV0JZXWjE+FvjJ3FP1hDIRZtyONz6dDQY9iA9Rs3OoFG1MtMe4nXIRx3F9OWT3Thi01CBTA1NlE326KO+g18KvXYs6yVx1y0evVB5/WXZ/OnqbWckQqjHgMB0l38D3OJJMkQVip/YY+6Xej5+J4u3UyRpli2ggnBm+FcX/waw3FmkBNBv1X8dQ4hQK7aLdNg0SaOK2dYz1lbulaCZH4eevbiwza2rTQNx8qZ6WIArvD6AoNf9/qMnmYfVrLfqhX4NdHWZHjGjNgwdHFsVZwQK270KOGU37dJvRrLXCsiHLi+YScyy3Sr6g+u+H6vowtrcUYzqEh/nFBi8HdZdBLZfd+BNktVNOpGBo7tQAP5hCNTeW6BnbX2lKwEY+t04ONune6FCBPrqKge2mBp0LVQQM60zncSVvhi/lWFXZ4dYEoST0cTLpq1A2r7mftXc=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: bbriggs/Legobot
    branch: master
